# Generated by Django 4.1.3 on 2023-05-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='others', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
