# Generated by Django 4.1.3 on 2023-05-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_city_product_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_availability',
            field=models.CharField(default='Not in stock', max_length=200),
        ),
    ]
