# Generated by Django 4.1.3 on 2023-05-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
