# Generated by Django 4.1.3 on 2023-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_shop_name_alter_product_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local_address',
            field=models.CharField(default=models.CharField(default='others', max_length=200), max_length=100),
        ),
    ]
