# Generated by Django 4.1.3 on 2023-04-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.EmailField(max_length=254)),
                ('shopkeeper_address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('re_enter_password', models.CharField(max_length=128)),
                ('shop_category', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('local_address', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
