# Generated by Django 4.1.3 on 2023-04-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
