# Generated by Django 4.1.3 on 2023-05-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shop_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='country_code',
            field=models.CharField(default=91, max_length=10),
        ),
    ]
